language: python

python:
      - "3.6"
services:
        - postgresql
before_script:
        - psql -c 'create database bigchat;' -U postgres
        - python3 BigChat/manage.py makemigrations
        - python3 BigChat/manage.py migrate
env:
      - DJANGO_VERSION=2.1.2
install:
      - python3 -m pip install -r BigChat/requirements.txt
      - python3 -m pip install psycopg2
      - python3 -m pip install python-codacy-coverage
      - python3 -m pip install coveralls
script:
      - coverage run --source='./BigChat/' manage.py test
after_success: coveralls


