language: python

python:
      - "3.6"
env:
      - DJANGO_VERSION=2.1.2
install:
      - python3 -m pip install -r BigChat/requirements.txt
      - python3 -m pip install coverage
      - python3 -m pip install python-codacy-coverage
script:
      - coverage run --source='BigChat/' manage.py test
      - coverage xml
      - python-codacy-coverage -r coverage.xml
